/*
 * @Author: 刘林
 * @Date: 2021-11-11 21:12:21
 * @LastEditors: 刘林
 * @LastEditTime: 2021-11-16 13:55:37
 */
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const reactRoutes = ['react/react-source1', 'react/react-source2',
  'react/react-source3', 'react/react-source4', 'react/webpack4-react'];

const cssRoutes = ['css/css3-card'];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // docs: {
  //   JS: [
  //     'js/doc1',
  //     {
  //       type: 'category',
  //       label: 'JavaScript设计模式',
  //       items: [
  //         'js/javascript-design-patterns/js-javascript-design-patterns-2-2',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-2-3',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-2-4',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-3-1',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-3-2',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-3-3',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-3-4',
  //         'js/javascript-design-patterns/js-javascript-design-patterns-3-5',
  //       ],
  //     },
  //   ],
  //   React: reactRoutes,
  //   CSS: cssRoutes,
  //   // Flutter: ['doc3'],
  // },
  flutter: [
    "flutter/flutter-intro"
  ],
  css: [
    "css/css-intro"
  ],
  js: [
    "js/js-intro",
    {
      type: 'category',
      label: 'JavaScript设计模式',
      items: [
        'js/javascript-design-patterns/js-javascript-design-patterns-2-2',
        'js/javascript-design-patterns/js-javascript-design-patterns-2-3',
        'js/javascript-design-patterns/js-javascript-design-patterns-2-4',
        'js/javascript-design-patterns/js-javascript-design-patterns-3-1',
        'js/javascript-design-patterns/js-javascript-design-patterns-3-2',
        'js/javascript-design-patterns/js-javascript-design-patterns-3-3',
        'js/javascript-design-patterns/js-javascript-design-patterns-3-4',
        'js/javascript-design-patterns/js-javascript-design-patterns-3-5',
      ],
    },
    {
      type: 'category',
      label: 'React',
      items: [
        'react/react-intro'
      ],
    }
  ],
  tools: {
    简介: ["tools/tools-intro"],
  },
};

module.exports = sidebars;
